- name: Install packages used by sys admins
  package:
    name: "{{ item }}"
    update_cache: yes
    state: present
  with_items:
    - sysdig
    - host
    - tcpdump
    - telnet
    - apt-transport-https

- name: Add an Apt signing key, uses whichever key is at the URL
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Add kubernetes repository
  template:
    src: kubernetes.list.j2
    dest: /etc/apt/sources.list.d/kubernetes.list
    owner: root
    group: root
    mode: '0600'

- name: Install kubernetes packages
  package:
    name: "{{ item }}"
    update_cache: yes
    state: present
  with_items:
    - kubectl
